### ISSUE TITLE
Message: necessary properties missing in userto object

### ISSUE THREAD

**Issue by Kathrin84** [gbateson/moodle-qtype_ordering#6] opened 2015-04-07 08:26 UTC
When a student submits his / her solution then follwing message occurs:

Necessary properties missing in userto object, fetching full record
line 95 of /lib/messagelib.php: call to debugging()
line 1451 of /mod/quiz/locallib.php: call to message_send()
line 1531 of /mod/quiz/locallib.php: call to quiz_send_notification()
line 1644 of /mod/quiz/locallib.php: call to quiz_send_notification_messages()
line ? of unknownfile: call to quiz_attempt_submitted_handler()
line 155 of /lib/classes/event/manager.php: call to call_user_func()
line 89 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
line 2411 of /lib/dml/moodle_database.php: call to core\event\manager::database_transaction_commited()
line 92 of /lib/dml/moodle_transaction.php: call to moodle_database->commit_delegated_transaction()
line 184 of /mod/quiz/processattempt.php: call to moodle_transaction->allow_commit()

Best regards,
Kathrin

**Comment by gbateson** [comment] 2015-04-07 10:07
Hi Kathrin,
it seems this error comes from the Moodle messaging system, when it is called from the Quiz module as it tries to send a notification message when an attempt is complete. 

None of those messages mention the ordering question type, so I don't think this error is caused by the ordering question. 

You can test this for yourelf by setting up another quiz with no ordering questions but with email notification turned on and see what happens. I think you will get the same error message.

I suggest you report this error either on the Moodle bug tracker, http://tracker.moodle.org, or on the Quiz module forum.

regards
Gordon

**Comment by Kathrin84** [comment] 2015-04-13 06:27
Thanks for your reply. As we've rolled out our update, I was able to test it within our production system and there was no such message in the error log.
So I think that this was caused by the disbaled eMail function within our testing instance.

I think this issue can be closed.

**Comment by gbateson** [comment] 2015-04-13 06:58
Thanks for the follow up information Kathrin. I will close this issue now, but feel free to reopen it if you wish.

**Closed by gbateson** 2015-04-13 06:58 UTC
