### ISSUE TITLE
3.8 not working

### ISSUE THREAD

**Issue by dinism** [gbateson/moodle-qtype_ordering#53] opened 2019-12-06 22:53 UTC
**I used moodle 3.7.2 with this plugin and all was ok**
![imagem](https://user-images.githubusercontent.com/14828021/70361937-2c35f880-187b-11ea-8908-01959b1d87ed.png)

**After i updated to 3.8 the dropdown menus doesn't work anymore. Any help?**
![imagem](https://user-images.githubusercontent.com/14828021/70361955-39eb7e00-187b-11ea-8d29-39cdbebb928b.png)

**How to TOTALLY remove the plugin?**

**Comment by gbateson** [comment] 2019-12-07 01:57
If you would like help to keep the ORdering plugin and get your menus working, please supply the folowing information:

- What version of the Ordering plugin are you using?
- What is the name of the theme you are using?

If you wish to remove this plugin, maybe the following page can help you:

- https://www.google.com/search?q=moodle+how+to+remove+a+plugin

**Comment by dinism** [comment] 2019-12-07 09:54
Theme Boost
Ordering version: 2019-10-24 (96)
Moodle version: (Build: 20191205)

Thanks

**Comment by dinism** [comment] 2019-12-07 13:04
![image](https://user-images.githubusercontent.com/14828021/70375115-08fa6000-18f2-11ea-8fe6-7661efa2aad6.png)

**Comment by dinism** [comment] 2019-12-07 16:50
When i try to execute:
".../moodle/admin/plugins.php?sesskey=el2jm1cXEk&uninstall=qtype_ordering&confirm=0&return=overview"
I got this
![imagem](https://user-images.githubusercontent.com/14828021/70377871-86819880-1911-11ea-963f-2e06fb28d4ee.png)

**Comment by gbateson** [comment] 2019-12-08 02:40
I think this happens if Ordering plugin is required by another plugin.
For example, the mod_reader plugin requires qtype_ordering. Do you have the mod_reader plugin installed?

**Comment by dinism** [comment] 2019-12-08 11:27
No.

**Comment by gbateson** [comment] 2019-12-09 06:58
It seems that Moodle will not allow the removal of a question type, if there are still questions of that type on the system, so you must remove all your Ordering questions first.

You can check where the ordering questions are if you do the following ...
(1) Navigte to Site administration => Plugins => Question types
(2) locate the row for the "Ordering" question type
(3) click on the number in the "No. questions" column

Once you have removed all the Ordering questions, you can remove the "qtype_ordering" plugin from the "Plugins overview" page.

If you do not wish to remove all the Ordering questions, or you cannot do so, then your last resort would be to simply remove the "question/type/ordering" folder from your server. However, if you do this you will break any quizzes that use Ordering questions.

**Comment by chris-blake** [comment] 2019-12-10 17:46
I've just gone through all my plugins while testing out my production site migration to moodle v3.8+ (12/4/2019 release date) and identified that the qtype_ordering plugin has javascript errors which break some of the site navigation. The navigation errors are mostly located in the Administration area and the upper right "profile" area navigation. I was using the boost theme and have been able to create, fix, and recreate the issue by installing this plugin, uninstalling the plugin and then re-installing the plugin while purging the site cache each time. This is definitely the plugin breaking the v3.8+ site. Please let me know if there is any other information you need.

**Comment by chris-blake** [comment] 2019-12-10 17:49
I was using the qtype_ordering plugin version titled "Release 2019-10-24 (96)"

**Comment by gbateson** [comment] 2019-12-11 13:47
Chris, what errors are reported in your browser's javascript console?

**Comment by gbateson** [comment] 2019-12-11 13:51
Chris, if you add the following line to you config.php, and then clear the JS cache, does the issue persist?
$CFG->cachejs = false;

**Comment by chris-blake** [comment] 2019-12-11 17:31
Yes, If I add that line to my config.php file the issue goes away (also if I change the application settings regarding cachejs by unchecking the setting box). Unfortunately, I cannot run my production site without js cache though. It' too big and busy and runs way too slow.

**Comment by gbateson** [comment] 2019-12-12 04:40
Thanks, that means that probably there is a missing semi-colon in one of the compacted JS files.

**Comment by gbateson** [comment] 2019-12-12 09:28
Dinism, and Chris-Blake,
I think this issue is now fixed in release 2019-12-12-(98) of the Ordering question type.
Please could you update this plugin on your Moodle site, and confirm that your admin menus now work as expected.
Thanks.

**Comment by gbateson** [comment] 2019-12-13 02:21
Dinism and Chris,
Thanks again for reporting this issue. I have now heard independantly that it is fixed in the latest release of the Ordering question, 2019-12-12 (98), so I will close this issue. Please feel free to reopen it, if you continue to have problems.

More details on the cause of this issue are available on the following link:
https://tracker.moodle.org/browse/MDL-67327

**Closed by gbateson** 2019-12-13 02:22 UTC

**Comment by chris-blake** [comment] 2019-12-13 02:47
Gordon,
I was just able to install it and test it on my production site with no issues. Thanks for being so responsive and I apologize for not being able to respond to your requests sooner. Thanks again, I really appreciate your work.


  *   Chris

**Comment by dinism** [comment] 2019-12-13 21:20
I confirm that admin menus now work as expected.
Thanks.
