### ISSUE TITLE
XML import and export missing gradingtype

### ISSUE THREAD

**Issue by dmarkwell** [gbateson/moodle-qtype_ordering#11] opened 2016-02-04 11:51 UTC
Hi Gordon,

I was pleased to find the ordering question type. It is very useful to us but I have found an issue with the XML import and export. I does not export the gradingtype that we use nor will it import it. Looking at the code I can see why as it only appears to switch on one specific type and otherwise exports blank and defaults to gradingtype 1 on import.
Is this something that could be fixed ... I would be happy even if it just imported the gradingtype numbers as our main use for the XML is to import from a spreadsheet format we use internally.
Anyway thanks for providing this useful question type.

David

**Comment by gbateson** [comment] 2016-02-04 13:43
Thanks very much for reporting this issue David and for investigating the workaround.

I have fixed the import/export code now and tested the fix on some simple Ordering questions exporting to XML and Gift format, and the iporting again from those files. It all seems to be working now. 

Please update the Ordering question type on your Moodle site at the next convenient opportunity and et me know if the issue is now resolved.

regards
Gordon

**Comment by gbateson** [comment] 2016-02-14 03:16
Hi David,
hopefully you have had time now to confirm that XML/gift export now includes the grading type.

I will close this issue now, but feel free to re-open it if you find the export functionality still has problems.

regards
Gordon

**Closed by gbateson** 2016-02-14 03:16 UTC
