### ISSUE TITLE
"Longest ordered subset" and "Longest contiguous subset"

### ISSUE THREAD

**Issue by dbauer-ets** [gbateson/moodle-qtype_ordering#30] opened 2018-11-25 18:44 UTC
Plugin Version: Release 2018-05-24 (69)
Moodle 3.4.2

Hello Gordon,

The names of these two grading types, "Longest ordered subset" and "Longest contiguous subset", seem to be reversed.

For the "Longest ordered subset" (should probably be called "Longest contiguous subset"), correct responses include several contiguous subsets, not just the longest. Is this the desired behavior? Does this conform to the definition given in the tooltip?
Of these several contiguous subsets identified in the correct responses, some contain just one item. Is this the desired behavior? I would think no.

**Comment by gbateson** [comment] 2018-11-26 00:19
Am I right in thinking this occurs only with "Item selection type" set to "Select a contiguous subset of items"? That is to say, if the "Item selection type" is "Select a random subset of items", then you get the expected behavior, yes?

**Comment by gbateson** [comment] 2018-11-26 01:20
I think this related to the issue you reported when "Item selection type" is set "Select a contiguous subset of items". Now that the selection of contiguous items is fixed, I think you will find that "Longest ordered subset" and "Longest contiguous subset" behave as described in the tool tip.

I would be grateful therefore, if you could you download the latest version of the plugin and confirm that the behavior is fixed. Many thanks.

**Comment by dbauer-ets** [comment] 2018-11-26 20:00
Here is an example with 10 draggable items: A, B, C, D, E, F, G, H, I, J.
"Select all items" is selected.

The "Longest ordered subset" seems to work properly, except that it has several subsets, not just the longest:
![otherquestiontypes20181126-1444](https://user-images.githubusercontent.com/22897609/49038283-7d041300-f18a-11e8-8f50-6998de16c63e.png)

The "Longest contiguous subset" also seems to work well, except that it also has several subsets, not just the longest:
![otherquestiontypes20181126-1439](https://user-images.githubusercontent.com/22897609/49038362-ba68a080-f18a-11e8-9f43-5fd673ded02c.png)

These behaviors make sense, but the names would have to be changed to "Ordered subsets" and "Contiguous subsets". Also, subsets of a single item should not be counted as correct.

**Comment by dbauer-ets** [comment] 2018-11-26 20:22
Here is the same example with 10 draggable items: A, B, C, D, E, F, G, H, I, J.
"Select all items" is selected.

The "Longest ordered subset" does not seem to work well:
- It has several subsets, not just the longest.
- It counts single item subsets as correct.
- It missed D, E, H, I, J, as the longest ordered subset.

![otherquestiontypes20181126-1517](https://user-images.githubusercontent.com/22897609/49039867-074e7600-f18f-11e8-83b1-0bb8a17a1fc6.png)

**Comment by gbateson** [comment] 2018-11-26 23:12
Regarding, "Longest contiguous subset", the example you give works exactly as expect.

"Contiguous" does not mean they need to occur next to each other in the answer. They can have other, incorrect, items between them. The important point is that they are contiguous in the original full sequence.

**Comment by gbateson** [comment] 2018-11-26 23:20
Regarding, "Longest ordered subset", I agree that the best answer is D-E-H-I-J.
There seems to be a problem. I will investigate and report back.

**Comment by dbauer-ets** [comment] 2018-11-27 18:45
Thank you for your replies. Regarding "Longest contiguous subset", I now understand better how this grading type works.

**Comment by gbateson** [comment] 2018-11-29 14:17
Hello Dominique,
Thank you for your patience but this was a rather tricky issue to investigate. 
Anyway, I believe I idenitified the cause the problem, and was able to implement a fix.
I would be grateful if you could download the latest version, 2018-11-29 (75), of the plugin from GitHub of the Moodle plugins repository, and confirm that it now behaves as expected, particularly in the questions using "Longest ordered/contiguous subset", such as though you gave earlier as examples.
If you concur, we can then close this issue.

**Comment by dbauer-ets** [comment] 2018-11-30 17:03
Moodle 3.4.2
Hello Gordon,
I installed version 2018-11-29 (75) from https://moodle.org/plugins/qtype_ordering. For the 
"Longest ordered subset", the longest subset: B, D, E, H, I, J appears to have been missed in the following example:

![otherquestiontypes20181130-1149](https://user-images.githubusercontent.com/22897609/49303437-af1db980-f497-11e8-9c7b-eb189a14000f.png)

**Comment by dbauer-ets** [comment] 2018-12-03 03:45
Hello Gordon,

I have written a small program that finds all the ordered subsets of any set of numbers that could be used for the Longest ordered subset grading type. If it helps you, you will find it at https://github.com/dbauer-ets/Ordered-subsets/blob/master/orderedSubsets.php.

**Comment by gbateson** [comment] 2018-12-11 15:14
Hi Dominique,
Thanks for letting me have a look at your code.
It gave me the idea to use for-loops rather than recursion when searching for ordered subsets.
I have updated the code in the Ordering module and released a new version on github.com and Moodle.org.
If you have time I would be grateful if you could try out the latest version, and let me know if it now works as expected on the examples you have given so far.
Many thanks
Gordon

**Comment by gbateson** [comment] 2018-12-12 04:42
Thanks Dominique. Safe travels!

**Comment by gbateson** [comment] 2018-12-25 02:50
Hi Dominique,
thanks for confirming that the longest subset code is now working as expected. 
I will close the Github issue now, but please reopen if you feel more work is required.

Also, thanks for sharing your website. 
If, on the main page for the "Ordering question type" course on moodleformulas.org, you would like to add my name, for example "The Ordering question type is maintained by Gordon Bateson, and you can download it from the Github.com or the plugins repository on Moodle.org", then I will add yours to the readme file for the this plugin.

**Closed by gbateson** 2018-12-25 02:50 UTC

**Comment by gbateson** [comment] 2018-12-26 01:35
Thanks. I have added a suitable credit to the [readme.txt](https://github.com/gbateson/moodle-qtype_ordering/blob/master/readme.txt)
