### ISSUE TITLE
The gradingtype_help string isn't displayed fully.

### ISSUE THREAD

**Issue by lucaboesch** [gbateson/moodle-qtype_ordering#57] opened 2020-11-02 08:25 UTC

**Comment by lucaboesch** [comment] 2020-11-02 08:30
In modern Moodle you have to use HTML markup to be properly displayed in a help text.
Thus, the gradingtype_help string is cut after the first line which makes it virtually useless.

<img width="643" alt="grafik" src="https://user-images.githubusercontent.com/377279/97846008-abcb8200-1ced-11eb-8e19-2759648af397.png">

Now, the text is rather a long one. I hope I've nailed it on how you wanted it to display originally/how it was displayed in older Moodles.

<img width="692" alt="grafik" src="https://user-images.githubusercontent.com/377279/97846139-df0e1100-1ced-11eb-8c47-d67bb8a631f8.png">


Best,
Luca

**Comment by lucaboesch** [comment] 2020-11-02 08:43
Shoudn't

Where there are multiple subsets of equal length, items in the subset that is found first, when searching from left
to right, will be displayed as correct.

be using "are" instead of "is"

Where there are multiple subsets of equal length, items in the subset that are found first, when searching from left
to right, will be displayed as correct.

There are two occurrencies of this.

**Comment by gbateson** [comment] 2020-11-04 00:39
Hi Luca,
thanks for reporting this issue and proposing a fix.
When you say "modern Moodle", I wonder which version you have tested. I was able to reproduce the issue as described in 3.7 using both the "Boost" and "Classic" themes. However, in 3.8, 3.9 and 4.0, using the "Boost" theme,  only the first line of the help text appeared, i.e. "Choose the type of grading calculation". Have you been able to confirm your fix in Moodle 3.8+?

**Comment by gbateson** [comment] 2020-11-04 02:10
Hi Luca,
thanks for reporting this issue.
It seems that from Moodle 3.8, the <dl> tags generated by the markdown are not displayed in the help popups.
One workaround is, as you have suggested to add html formatting, but this may cause for trouble for the translators who wouold have to keep the tags in their translations.
Therefore, I prefer to alter the markdown to the following (see below).
Notice that at the end of each heading line, marked with double asterisks, there are two spaces, "  ", to force a single line break instead of a new parragraph.
==============================
Choose the type of grading calculation.

**All or nothing**  
    If all items are in the correct position, then full marks are awarded. Otherwise, the score is zero.

**Absolute position**  
    An item is considered correct if it is in the same position as in the correct answer. The highest possible score for the question is **the same as** the number of items displayed to the student.

**Relative to correct position**  
    An item is considered correct if it is in the same position as in the correct answer. Correct items receive a score equal to the number of items displayed minus one. Incorrect items receive a score equal to the number of items displayed minus one and minus the distance of the item from its correct position. Thus, if ***n*** items are displayed to the student, the number of marks available for each item is ***(n - 1)***, and the highest mark available for the question is ***n x (n - 1)***, which is the same as ***(n² - n)***.

**Relative to the next item (excluding last)**  
    An item is considered correct if it is followed by the same item as it is in the correct answer. The item in the last position is not checked. Thus, the highest possible score for the question is **one less than** the number of items displayed to the student.

**Relative to the next item (including last)**  
    An item is considered correct if it is followed by the same item as it is in the correct answer. This includes the last item which must have no item following it. Thus, the highest possible score for the question is **the same as** the number of items displayed to the student.

**Relative to both the previous and next items**  
    An item is considered correct if both the previous and next items are the same as they are in the correct answer. The first item should have no previous item, and the last item should have no next item. Thus, there are two possible points for each item, and the highest possible score for the question is **twice** the number of items displayed to the student.

**Relative to ALL previous and next items**  
    An item is considered correct if it is preceded by all the same items as it is in the correct answer, and it is followed by all the same items as it is in the correct answer. The order of the previous items does not matter, and nor does the order of the following items. Thus, if ***n*** items are displayed to the student, the number of marks available for each item is ***(n - 1)***, and the highest mark available for the question is ***n x (n - 1)***, which is the same as ***(n² - n)***.

**Longest ordered subset**  
    The grade is the number of items in the longest ordered subset of items. The highest possible grade is the same as the number of items displayed. A subset must have at least two items. Subsets do not need to start at the first item (but they can) and they do not need to be contiguous (but they can be). Where there are multiple subsets of equal length, items in the subset that is found first, when searching from left to right, will be displayed as correct. Other items will be marked as incorrect.

**Longest contiguous subset**  
    The grade is the number of items in the longest contiguous subset of items. The highest possible grade is the same as the number of items displayed. A subset must have at least two items. Subsets do not need to start at the first item (but they can) and they MUST BE CONTIGUOUS. Where there are multiple subsets of equal length, items in the subset that is found first, when searching from left to right, will be displayed as correct. Other items will be marked as incorrect.

**Comment by gbateson** [comment] 2020-11-04 02:45
Regarding the scolling. I tried adding the bootstrap classes, "mh-100" (to limit the height) and "overflow-auto" (to request scrolling) to the main div containing the help popup content, but it had no effect :-(
I hope we can find a workaround for that, because I agree with you that the current help popups can toooooo looooong!

**Comment by gbateson** [comment] 2020-11-04 04:22
I just noticed that you asked about "is" and "are". No change is required because the "is" refers to "the subset". 
i.e. "items in (the subset that is found first)". We could rephrase is as "items in the first subset found ... will be be displayed as correct"

**Comment by wiebkemueller-hsh** [comment] 2021-01-20 10:29
> 
> 
> Regarding the scolling. I tried adding the bootstrap classes, "mh-100" (to limit the height) and "overflow-auto" (to request scrolling) to the main div containing the help popup content, but it had no effect :-(
> I hope we can find a workaround for that, because I agree with you that the current help popups can toooooo looooong!

Hi all, for those who use it, the theme boost campus provides an option to display help texts in modal dialogue instead of popups. but this would mean all popus are replaced by modal dialogues

https://github.com/moodleuulm/moodle-theme_boost_campus#show-help-texts-in-a-modal-dialogue

Regards
Wiebke

**Comment by gbateson** [comment] 2021-09-14 06:29
Hi Luca,
thanks again for identifying the problem with the long help messages and suggesting a possible workaround.
In the end, I decided to use the following syntax, as this seems to work and does not require HTML tags:

\*\*All or nothing\*\*  
\&nbsp; If all items are in the correct position ...

As I mentioned earlier, there are two spaces, " ", to force a single line break after the title. The "\$nbsp;" is to force a small indentation at the beginning of the explanation.

**Closed by gbateson** 2021-09-14 06:29 UTC
