### ISSUE TITLE
Feedback shows final word in a horizontal sentence in a white color

### ISSUE THREAD

**Issue by donhinkelman** [gbateson/moodle-qtype_ordering#54] opened 2019-12-29 13:00 UTC
This is a concern that puzzles me. When I submit a horizontal ordering exercise (jumbled words to compose a sentence), the feedback shows correctly ordered words in green, and incorrectly ordered words in red, except for the final item, which is shown in white background. This confuses me and I think the final item should be either red or green.

**Comment by donhinkelman** [comment] 2019-12-29 13:04
<img width="946" alt="Screen Shot 2019-12-29 at 15 47 59" src="https://user-images.githubusercontent.com/12912710/71557263-26e95980-2a87-11ea-8807-520e6abdfaa9.png">

**Comment by donhinkelman** [comment] 2019-12-31 05:47
After more testing, I found that the above behavior happens when the following setting is applied: **Relative to the next item (excluding last)**. **This setting is the current default.** I kept that criteria because it seemed the most fair. However, as you can see above, it is confusing to students and to me. I changed to a setting of Absolute position, and I noticed expected green coloring in the last box. See screenshot. I think **the default for ordering should be absolute position**. There are so many unpredictable and confusing results possible for this question type, that I recommend common defaults, and reducing the number of options for ordering. It is also very difficult to troubleshoot problems because the teacher must not switch roles, but actually log in as a student and observe what feedback and grading they received. I spent perhaps 15 hours troubleshooting this question type for six auto-essay grading activities. This is because I had to actually see the students doing the activity and observe their screens to figure out what the problem was. I recommend removing the option of Relative to next item (excluding last), and making absolute position the new default.

**Comment by donhinkelman** [comment] 2019-12-31 05:48
<img width="1055" alt="Screen Shot 2019-12-31 at 14 18 33" src="https://user-images.githubusercontent.com/12912710/71611480-92910b00-2bdc-11ea-8929-61067eda34e5.png">

**Comment by donhinkelman** [comment] 2019-12-31 05:55
I will be uploading a course with heavy classroom-tested use of Essay Auto-grade. I can see that teachers will need extensive training in common mistakes and other confusing points before they can use this plugin. I will try to include some warning and advice in the course. And of course, I would like your advice as well.

**Comment by gbateson** [comment] 2020-01-03 05:23
Hi Don,
You raise several points, so I will try to respond to each separately.
(1) coloring of last item when using "Relative to the next item (excluding last)"
Personally, I do not think the last item should be red or green, because it does affect the score, as indicated in the title of the ordering type. Perhaps, "Relative to the next item (including last)" would behave more as you expect?

(2) coloring of items followed by incorrect item in "Relative to the next item (excluding last)"
Again, I do not think the coloring of these items should be green, because this ordering type marks an item as correct only if it is followed by the expected item.

(3) "Switch role" does not work as expected when "teacher" switches to "student" role
Could you describe in a little more detail what the issue is here. I understand that when logged in as a teacher, you switched to student role, but got an unexpected behavior. What was the expected behavior, and what actually happened?

(4) default ordering should be "Absolute position"
Actually, "Absolute position" is the initial default grading type. Thereafter, the default used on a new ordering question is the grading type used on the last edited question. 

(5) reduce number of ordering options
I don't think we can do this without inconveniencing people who are already using one the options that are removed. Each option is there because someone requested.

(6) "I would like your advice as well"
Hmm, I'm not sure what you would like advice about. Please could you elaborate ;-)

**Comment by donhinkelman** [comment] 2020-02-05 14:04
If Absolute Position is indeed the default, then that solves the problems I was having. I wonder how the other default got started. I guess I inadvertantly set it wrongly and then all subsequent questions followed that setting. As for Relative to next item (excluding last) remaining in the list, are you sure someone is really continuing to use this? It is a quagmire waiting for new users like me to get stuck in. You have given the advice I sought. Thank you!  And now I only recommend, putting in warning to avoid "Relative to the next item (excluding last)" for beginners because many unexpected behaviors can occur.

**Comment by gbateson** [comment] 2021-01-29 03:21
Thanks for your feedback, Don. I will close this issue for the Ordering question type, but please reopen it if you feel it still needs to be addressed.

**Closed by gbateson** 2021-01-29 03:21 UTC
